# Generated by Django 5.2.11 on 2026-02-20 18:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_party'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='core.organization', verbose_name='المنظمة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.category', verbose_name='الفئة الأب')),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'فئات المنتجات',
                'db_table': 'categories',
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='الرمز')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(default='قطعة', max_length=20)),
                ('track_serial', models.BooleanField(default=False, verbose_name='تتبع Serial')),
                ('min_stock', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category', verbose_name='الفئة')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.organization', verbose_name='المنظمة')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'db_table': 'products',
                'ordering': ['name'],
                'unique_together': {('organization', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('in', 'إدخال'), ('out', 'إخراج'), ('transfer', 'تحويل'), ('adjust', 'تسوية'), ('return_in', 'مرتجع إدخال'), ('return_out', 'مرتجع إخراج')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='سعر الشراء')),
                ('extra_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='المصاريف الإضافية')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='التكلفة الفعلية')),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='سعر البيع')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_costs', to='core.branch', verbose_name='الفرع')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'تكلفة منتج',
                'verbose_name_plural': 'تكاليف المنتجات',
                'db_table': 'product_costs',
                'unique_together': {('product', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='ProductSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('in_stock', 'في المخزون'), ('sold', 'مباع'), ('reserved', 'محجوز'), ('defective', 'معطل')], default='in_stock', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_serials', to='core.branch', verbose_name='الفرع')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'Serial',
                'verbose_name_plural': 'Serial Numbers',
                'db_table': 'product_serials',
                'ordering': ['serial_number'],
                'unique_together': {('product', 'serial_number')},
            },
        ),
    ]
