# Generated by Django 5.2.11 on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(
                condition=models.Q(('code__gt', '')),
                fields=('organization', 'code'),
                name='category_org_code_unique_when_not_empty',
            ),
        ),
    ]
