# Generated by Django 5.2.11 on 2026-02-20 18:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_party'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_number', models.CharField(max_length=50, unique=True)),
                ('purchase_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكدة'), ('cancelled', 'ملغاة')], default='draft', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.party', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'فاتورة مشتريات',
                'verbose_name_plural': 'فواتير المشتريات',
                'db_table': 'purchases',
                'ordering': ['-purchase_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.product', verbose_name='المنتج')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchase', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'بند مشتريات',
                'verbose_name_plural': 'بنود المشتريات',
                'db_table': 'purchase_items',
            },
        ),
    ]
