# Generated by Django 5.2.11 on 2026-02-20 17:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('is_system', models.BooleanField(default=False, verbose_name='حساب نظام')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'دليل الحسابات',
                'db_table': 'accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('natural_balance', models.CharField(choices=[('D', 'مدين'), ('C', 'دائن')], max_length=1)),
            ],
            options={
                'verbose_name': 'نوع حساب',
                'verbose_name_plural': 'أنواع الحسابات',
                'db_table': 'account_types',
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'مركز تكلفة',
                'verbose_name_plural': 'مراكز التكلفة',
                'db_table': 'cost_centers',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_number', models.CharField(max_length=50, unique=True)),
                ('entry_date', models.DateField()),
                ('journal_type', models.CharField(choices=[('manual', 'يدوي'), ('auto', 'تلقائي'), ('compound', 'مركب')], default='manual', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('is_posted', models.BooleanField(default=False)),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
            ],
            options={
                'verbose_name': 'قيد يومي',
                'verbose_name_plural': 'القيود اليومية',
                'db_table': 'journal_entries',
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('line_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'بند قيد',
                'verbose_name_plural': 'بنود القيود',
                'db_table': 'journal_lines',
                'ordering': ['line_order'],
            },
        ),
    ]
