# Generated by Django 5.2.11 on 2026-02-21 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('core', '0003_add_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفترة')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(verbose_name='إلى تاريخ')),
                ('is_locked', models.BooleanField(default=False, verbose_name='مقفولة')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_periods', to='core.organization', verbose_name='المنظمة')),
            ],
            options={
                'verbose_name': 'فترة مالية',
                'verbose_name_plural': 'الفترات المالية',
                'db_table': 'fiscal_periods',
                'ordering': ['-start_date'],
            },
        ),
    ]
