# Generated by Django 5.2.11 on 2026-02-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('', 'بدون'), ('manager', 'مدير'), ('accountant', 'محاسب'), ('cashier', 'كاشير'), ('warehouse', 'مخزن')], default='', max_length=20, verbose_name='الدور'),
        ),
    ]
