# Generated by Django 5.2.11 on 2026-02-20 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_party'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-id'], 'verbose_name': 'O_U?O1/U.U,O"U^O ', 'verbose_name_plural': 'O U,U.O_U?U^O1O O U^O U,U.U,O"U^O O O'},
        ),
        migrations.AddField(
            model_name='payment',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.party', verbose_name='Party'),
        ),
        migrations.AddField(
            model_name='payment',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='purchases.purchase', verbose_name='Purchase'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales.sale', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.branch', verbose_name='O U,U?OO1'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cash_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='treasury.cashaccount', verbose_name='O-O3O O U,OrOUSU+c'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('receipt', 'U.U,O"U^O O O'), ('payment', 'U.O_U?U^O1O O')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='source_type',
            field=models.CharField(choices=[('customer', 'O1U.USU,'), ('supplier', 'U.U^OO_'), ('other', 'OOrOU%')], default='other', max_length=20),
        ),
    ]
