# Generated by Django 5.2.11 on 2026-02-20 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('device_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد التنفيذ'), ('done', 'منتهي'), ('cancelled', 'ملغى')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_orders', to='core.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'أمر صيانة',
                'verbose_name_plural': 'أوامر الصيانة',
                'db_table': 'maintenance_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
