# Generated by Django 5.2.11 on 2026-02-21 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('treasury', '0002_add_party_invoice_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_sales', to='treasury.cashaccount', verbose_name='حساب الخزينة (للبيع النقدي)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('credit', 'آجل'), ('cash', 'نقدي')], default='credit', max_length=20, verbose_name='نوع الدفع'),
        ),
    ]
