# Generated by Django 5.2.11 on 2026-02-21 16:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_payment_type_cash_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'غير مسدد'), ('partial', 'مسدد جزئي'), ('paid', 'مسدد')], default='unpaid', max_length=20, verbose_name='حالة السداد'),
        ),
    ]
